### PR TITLE
Updating C# quickstart and tutorial Dapr SDK references to 1.8.  They…

### LINKED ISSUE #704: Dapr quickstarts and tutorials need updates to use latest 1.8+ references
The references are woefully old, e.g. 1.5-1.7.  

## Expected Behavior

We want quickstarts to snap to latest for best stability and features, which currently is 1.8.

### PR DESCRIPTION
**Pull request by paulyuk**
This fixes C# references for Dapr SDK * (client and server) by moving up to 1.8

Signed-off-by: Paul Yuknewicz <paulyuk@microsoft.com>

## Issue reference

fixes #704 

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [x] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

**Review by halspang — APPROVED** [review]

**Comment by amulyavarote** [comment]
Changes look good to me! But rerunning the failed workflows.

**Review by msfussell — DISMISSED** [review]

**Review by amulyavarote — CHANGES_REQUESTED** [review]
We have conflicts. Can we resolve the conflicts and fix the workflows before we merge this PR?

**Comment by paulyuk** [comment]
@msfussell -- the pubsub python validation fails due to known issue: https://github.com/dapr/quickstarts/issues/715

So this is expected check.

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
