### PR TITLE
Java quickstarts auto validate for pubsub, state mgmt and service invo

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Java quickstarts auto validate changes

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: NA

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [x] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

**Comment by amulyavarote** [comment]
@pravinpushkar Can we take a look at docker install version in the workflow? Docker install is getting stuck.

**Comment by pravinpushkar** [comment]
> @pravinpushkar Can we take a look at docker install version in the workflow? Docker install is getting stuck.

I will take a look.

**Comment by pravinpushkar** [comment]
https://github.com/docker-practice/actions-setup-docker/issues/19

**Comment by khs1994** [comment]
try test on `macos-10.12`

**Review by amulyavarote — APPROVED** [review]

**Pull request merged**
