### PR TITLE
Update observability quickstart sample to show OpenTelemetry exporter usage

### PR DESCRIPTION
**Pull request by tcnghia**
# Description

Update observability quickstart sample to show OpenTelemetry exporter -> Zipkin usage.

Please note that in this PR the OpenTelemetry Collector Helm chart was used. This is so that we don't have to maintain all the independent components ourselves, but instead rely on the Helm chart parameters. I will follow up with another PR to switch the OpenTelemetry how-to in dapr/docs to use the same for simplicity & consistency.

## Issue reference

Please reference the issue this PR will close: #324 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary

### CODE REVIEW

**Comment by mukundansundar** [comment]
@tcnghia If zipkin exporters are going to be deprecated. Please create corresponding issue in CLI to replace zipkin with opentelemetry configurations. https://github.com/dapr/cli/blob/master/pkg/standalone/standalone.go#L888

**Comment by tcnghia** [comment]
> @tcnghia If zipkin exporters are going to be deprecated. Please create corresponding issue in CLI to replace zipkin with opentelemetry configurations. https://github.com/dapr/cli/blob/master/pkg/standalone/standalone.go#L888

+1, thanks

I've added you as a reviewer. Can you please help trying out the new instructions?  Thanks!

**Comment by orizohar** [comment]
We should keep the quickstarts simple (they need to be a quick way to show value of the specific area) so I don't think we need to have options (we already have an option for each quickstart to run locally vs k8s - this needs to be added here as mentioned in https://github.com/dapr/quickstarts/issues/288 but outside the scope of this PR).
If using the Open Telemetry collector is where we are headed we should just have users do that and remove the other option.

**Review by msfussell — COMMENTED** [review]
The decision here then is to have the sample use OT for the collector/exporter pushing to ZipKin going forward and to remove the localforwarder option.  Can we include issue #288 at the same time, and I do not think we have to say which app is used, since this can either be the hello world or distributed calc examples.

**Comment by tcnghia** [comment]
closing -- we are reconsidering our approach here. will replace with follow ups.

**Pull request closed without merging**
