### PR TITLE
Fixing dead links in Distributed Calculator/Middleware READMEs

### PR DESCRIPTION
**Pull request by daniv-msft**
# Description

This link doesn't redirect to the right page anymore: https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster
Updated to use instead: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/

## Issue reference

None that I'm aware of

## Checklist

Only README update, no code change

### CODE REVIEW

**Review by wcs1only — COMMENTED** [review]
Nice catch! Can you fix these others, while we're at it?

```
 % find . -name "*.md" -maxdepth 2 | xargs grep install-dapr-on-a-kubernetes-cluster
./distributed-calculator/README.md:1. Dapr-enabled Kubernetes cluster. Follow [these instructions](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster) to set this up.
./middleware/README.md:- [Dapr enabled Kubernetes cluster](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
./hello-kubernetes/README.md:Once you have a cluster, follow the steps below to deploy Dapr to it. For more details, look [here](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
./observability/README.md:2. [Install Dapr on Kubernetes](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster).
./secretstore/README.md:Once you have a cluster, follow the steps below to deploy Dapr to it. For more details, look [here](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
./bindings/README.md:- [Dapr enabled Kubernetes cluster](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
```

**Comment by daniv-msft** [comment]
> Nice catch! Can you fix these others, while we're at it?
> 
> ```
>  % find . -name "*.md" -maxdepth 2 | xargs grep install-dapr-on-a-kubernetes-cluster
> ./distributed-calculator/README.md:1. Dapr-enabled Kubernetes cluster. Follow [these instructions](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster) to set this up.
> ./middleware/README.md:- [Dapr enabled Kubernetes cluster](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
> ./hello-kubernetes/README.md:Once you have a cluster, follow the steps below to deploy Dapr to it. For more details, look [here](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
> ./observability/README.md:2. [Install Dapr on Kubernetes](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster).
> ./secretstore/README.md:Once you have a cluster, follow the steps below to deploy Dapr to it. For more details, look [here](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
> ./bindings/README.md:- [Dapr enabled Kubernetes cluster](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
> ```

Absolutely! Thanks for catching

**Comment by daniv-msft** [comment]
@wcs1only Updated! Please note that for two READMEs (secretstore and hello-kubernetes), I slightly updated the surrounding text as else the same URL would have been used twice in almost the same location. Please don't hesitate if another alternative would look better to you.

**Review by wcs1only — APPROVED** [review]
Thanks for helping us make our quickstarts better!

**Pull request merged**
