### PR TITLE
Update Python pub_sub fastapi example

### PR DESCRIPTION
**Pull request by inirudebwoy**
Signed-off-by: Michał Klich <michal@klichx.dev>

# Description

I have updated FastAPI example attached to `pub_sub` for Python.
It had not worked correctly.

## Issue reference

Sorry, but there is no issue.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

**Comment by yaron2** [comment]
@inirudebwoy apologies the review has taken so long. can you please resolve the conflict?

**Comment by inirudebwoy** [comment]
@yaron2 No worries. I have resolved the conflicts. There seems to be some issue with signature.

**Comment by inirudebwoy** [comment]
@yaron2 No worries. I have resolved the conflicts. There seems to be some issue with signature.

**Comment by amulyavarote** [comment]
@inirudebwoy Can you please take the recent changes from master and rebase this with master and push the changes? And also, can you please fix DCO as well.

**Comment by amulyavarote** [comment]
> @amulyavarote Sure thing. I hope it's fine now.

Can you please fix the build errors? The changes look good to me. Lets make sure these changes work before merging by seeing the successful validations.

**Comment by inirudebwoy** [comment]
I really like the way you test documentation 👍my code has failed on something I have not changed. Or is it related?

Best regards
Michał Klich

**Comment by amulyavarote** [comment]
> I really like the way you test documentation 👍my code has failed on something I have not changed. Or is it related? Best regards Michał Klich
> […](#)
> On 1 May 2022, at 1:09 AM, Yaron Schneider ***@***.***> wrote: ﻿ Assigned #635 to @inirudebwoy. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.

Can you please throw some light on this? What error are you getting?

**Comment by yaron2** [comment]
@amulyavarote I think mac validations are failing regardless of this PR.

**Comment by amulyavarote** [comment]
> @amulyavarote I think mac validations are failing regardless of this PR.

@yaron2 Usually rerunning the tests fixes it. I did it again. The previous PRs build passed.

**Comment by yaron2** [comment]
> > @amulyavarote I think mac validations are failing regardless of this PR.
> 
> @yaron2 Usually rerunning the tests fixes it. I did it again. The previous PRs build passed.

I think it's consistent..

**Comment by amulyavarote** [comment]
> > > @amulyavarote I think mac validations are failing regardless of this PR.
> > 
> > 
> > @yaron2 Usually rerunning the tests fixes it. I did it again. The previous PRs build passed.
> 
> I think it's consistent..

Distributed Calculator and Bindings are failing inconsistently.

**Comment by inirudebwoy** [comment]
Do you need my help in solving this? I'm not able to run Github Actions on my account unfortunately.

**Comment by yaron2** [comment]
@amulyavarote can we merge this PR?

**Review by amulyavarote — APPROVED** [review]

**Comment by amulyavarote** [comment]
> @amulyavarote can we merge this PR?

Yes!!

**Comment by amulyavarote** [comment]
> Do you need my help in solving this? I'm not able to run Github Actions on my account unfortunately.

I pushed a change. Can you please rebase now? I will merge the PR after the builds succeed.

**Comment by inirudebwoy** [comment]
> I pushed a change. Can you please rebase now? I will merge the PR after the builds succeed.

I have rebased it.

**Review by amulyavarote — APPROVED** [review]

**Pull request merged**
