### PR TITLE
Updated the docker file to use linux arm image

### PR DESCRIPTION
**Pull request by Arashrohani**
Signed-off-by: Arash Rohani <Arash.Rohani@gmail.com>

# Description

Updated the C# subscriber docker file to use linux arm image.
Hey @paulyuk It seems that there is one issue with regards to building image for C# in linux arm environment, I found a workaround and made the necessary changes accordingly, would you please merge this with master to test?

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [x] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

**Comment by amulyavarote** [comment]
@Arashrohani The tutorials workflow is still failing. Can you please look into it?

**Comment by Arashrohani** [comment]
@paulyuk @amulyavarote As I explained in PR description the issue is still the same, this needs to be merged to master so the build step can push the new image in order for tests to be passed.
if you look at master branch, this step is failing "Build linux_arm binaries", I looked at it and noticed that this is the error:

**A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders
The command '/bin/sh -c dotnet restore "csharp-subscriber.csproj"' returned a non-zero code: 131
make: *** [../docker.mk:42: build-csharp-subscriber] Error 131

Error: Process completed with exit code 2.**

I found a workaround and created this PR to fix that. The image is building locally but it needs to be merged in your environment to test it.
Would you please merge this with master and see what will happen with that step?

**Comment by amulyavarote** [comment]
> @paulyuk @amulyavarote As I explained in PR description the issue is still the same, this needs to be merged to master so the build step can push the new image in order for tests to be passed. if you look at master branch, this step is failing "Build linux_arm binaries", I looked at it and noticed that this is the error:
> 
> **A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders The command '/bin/sh -c dotnet restore "csharp-subscriber.csproj"' returned a non-zero code: 131 make: *** [../docker.mk:42: build-csharp-subscriber] Error 131
> 
> Error: Process completed with exit code 2.**
> 
> I found a workaround and created this PR to fix that. The image is building locally but it needs to be merged in your environment to test it. Would you please merge this with master and see what will happen with that step?

Thank you so much for the explanation. @paulyuk Any inputs on this?

**Comment by Arashrohani** [comment]
@paulyuk @amulyavarote This is the workaround: https://github.com/dotnet/dotnet-docker/issues/1537#issuecomment-615269150

**Comment by paulyuk** [comment]
> > @paulyuk @amulyavarote As I explained in PR description the issue is still the same, this needs to be merged to master so the build step can push the new image in order for tests to be passed. if you look at master branch, this step is failing "Build linux_arm binaries", I looked at it and noticed that this is the error:
> > **A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders The command '/bin/sh -c dotnet restore "csharp-subscriber.csproj"' returned a non-zero code: 131 make: *** [../docker.mk:42: build-csharp-subscriber] Error 131
> > Error: Process completed with exit code 2.**
> > I found a workaround and created this PR to fix that. The image is building locally but it needs to be merged in your environment to test it. Would you please merge this with master and see what will happen with that step?
> 
> Thank you so much for the explanation. @paulyuk Any inputs on this?

We don't believe this dockerfile will try to build and fail on amd64?

**Comment by Arashrohani** [comment]
Hey @paulyuk, Did you have a chance to take a look at this link: https://github.com/dotnet/dotnet-docker/issues/1537#issuecomment-615269150

I found this from this pattern: https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile.debian-arm32

It seems that this is the way to fix the build image on amd64 hosts for linux arm v7. The easiest way to test this is to merge this with master or if there is a way to enable that step "Build linux_arm binaries" for this branch?

Please advice how we can proceed to fix this.

**Comment by paulyuk** [comment]
> Hey @paulyuk, Did you have a chance to take a look at this link: [dotnet/dotnet-docker#1537 (comment)](https://github.com/dotnet/dotnet-docker/issues/1537#issuecomment-615269150)
> 
> I found this from this pattern: https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile.debian-arm32
> 
> It seems that this is the way to fix the build image on amd64 hosts for linux arm v7. The easiest way to test this is to merge this with master or if there is a way to enable that step "Build linux_arm binaries" for this branch?
> 
> Please advice how we can proceed to fix this.

I did - thanks.  What's bugging me is the dockerfile is now architecture dependent.  But in the make process we dynamically build each architecture in the foreach, using the more generic image tag that is already multiarch. I can try it just doesn't make sense to me how this will integrate.

**Comment by Arashrohani** [comment]
@paulyuk Oh I see what you mean, unfortunately I didn't know anything about the make process, So this will probably fix that issue but it may create another issue because of the architecture dependent.
Please let me know how we can fix this issue? Can I look at the make file to learn about the process?

**Comment by paulyuk** [comment]
@Arashrohani totally.  There is a bit of inception here :)

Please take a look at this makefile that is responsible for docker image build, tag and push: https://github.com/dapr/quickstarts/blob/master/docker.mk#L27

what I believe we want to do is find a base image that is already multiarch, and then this build process will add the right tags.  I have to investigate why this dotnet base image is different than the alpine images we use for node and python.

**Comment by Arashrohani** [comment]
@paulyuk I was exactly looking at that sample :)
It seems that because of that issue (there is a problem with multistage build for the multiarch dotnet docker image) they had done it that way.
No worries, I will update the makefile and docker file for csharp-subscriber and create a new PR.
Thanks for your help.

**Comment by paulyuk** [comment]
Thank you so much -- we're close

**Pull request merged**
