### PR TITLE
Adding "slowness" back to Observability tutorial

### PR DESCRIPTION
**Pull request by paulyuk**
# Description

Updated Kubernetes deploy manifests to pull the "slow" container image for multiply app, and then updated Readme to filter zipkin by slow requests.  

## Issue reference

#619 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [x] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

### CODE REVIEW

**Review by amulyavarote — APPROVED** [review]

**Comment by paulyuk** [comment]
I would still like an RCA why multiplyapp deployment shows as unchanged in kubernetes/kind, but I have at least achieved the two goals of 1) the tests pass and 2) the observability tutorial delivers on its promise of finding slow requests.  

For these reasons I suggest we take and merge this.

**Comment by msfussell** [comment]
The 19411 change is simply to avoid the clash between self hosted and K8s if running on the same machine correct?

**Comment by paulyuk** [comment]
> The 19411 change is simply to avoid the clash between self hosted and K8s if running on the same machine correct?

Yes exactly.  This tutorial starts users in the self hosted mode with zipkin, and then transitions into the kubernetes mode, walking them straight into the clash.  Given we're port mapping/forwarding anyway I feel this is the ideal solution.

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
